antora:
  extensions:
    - '@antora/lunr-extension' # Adds search functionality

site:
  title: DocKo Docs
  start_page: personal-site-docs::index.adoc
  url: https://docko.dev
    
content:
  sources:
    - url: https://github.com/doc-ko/doc-ko.github.io.git
      branches: HEAD
      start_path: docs
    - url: https://github.com/doc-ko/antora-site.git
      branches: HEAD
      start_path: docs

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true